// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkoUI72EYLiHWBUI8_E9pPCDHS8UsoCZ0',
    appId: '1:72082041804:web:a4392dbbc78253e07b8b69',
    messagingSenderId: '72082041804',
    projectId: 'riverpodtodo-95185',
    authDomain: 'riverpodtodo-95185.firebaseapp.com',
    storageBucket: 'riverpodtodo-95185.appspot.com',
    measurementId: 'G-42WWFYCP0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaVw7yhXnsty4zcP4BRpgefWHxE6KJvVU',
    appId: '1:72082041804:android:e3cb0b302f4576367b8b69',
    messagingSenderId: '72082041804',
    projectId: 'riverpodtodo-95185',
    storageBucket: 'riverpodtodo-95185.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_oGNZuhXrCMJwb5Sg1uz5idc7QprAQBY',
    appId: '1:72082041804:ios:080332d7ebc013247b8b69',
    messagingSenderId: '72082041804',
    projectId: 'riverpodtodo-95185',
    storageBucket: 'riverpodtodo-95185.appspot.com',
    iosBundleId: 'com.example.riverpodTodo',
  );
}
